---
blank_issues_enabled: false
contact_links:
  - name: Plaid SDK for Laravel Community Support
    url: https://github.com/caashapp/plaid-sdk-laravel/discussions
    about: Please ask and answer questions here.
